// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJxPWQQQqoPeXwgEF2lBYKNkPDoif0c_I',
    appId: '1:238089612667:web:fed54d61625836d42c61de',
    messagingSenderId: '238089612667',
    projectId: 'tuktuk-service-2026',
    authDomain: 'tuktuk-service-2026.firebaseapp.com',
    storageBucket: 'tuktuk-service-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgJIl3qBRDqbe5Kq_9TmamnnFHmCmpFA',
    appId: '1:238089612667:android:a4318700b93fb52b2c61de',
    messagingSenderId: '238089612667',
    projectId: 'tuktuk-service-2026',
    storageBucket: 'tuktuk-service-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2THmADtGsIqDjzXKLta_ufzH_LEMckA',
    appId: '1:238089612667:ios:c0eba820e9f207e02c61de',
    messagingSenderId: '238089612667',
    projectId: 'tuktuk-service-2026',
    storageBucket: 'tuktuk-service-2026.firebasestorage.app',
    iosBundleId: 'com.example.tuktuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv2THmADtGsIqDjzXKLta_ufzH_LEMckA',
    appId: '1:238089612667:ios:c0eba820e9f207e02c61de',
    messagingSenderId: '238089612667',
    projectId: 'tuktuk-service-2026',
    storageBucket: 'tuktuk-service-2026.firebasestorage.app',
    iosBundleId: 'com.example.tuktuk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJxPWQQQqoPeXwgEF2lBYKNkPDoif0c_I',
    appId: '1:238089612667:web:818344ed442f11dd2c61de',
    messagingSenderId: '238089612667',
    projectId: 'tuktuk-service-2026',
    authDomain: 'tuktuk-service-2026.firebaseapp.com',
    storageBucket: 'tuktuk-service-2026.firebasestorage.app',
  );
}
